### ISSUE TITLE
Always Checked

### ISSUE THREAD

**Issue by EAnushan** [kartik-v/yii2-widget-switchinput#16]
Try the following:
```
echo SwitchInput::widget([
    'name' => 'mycheckbox',
    'value' => 6,
    'options' => [
        'checked' => FALSE,
    ],
    'pluginOptions' => [
        'onText' => 'Yes',
        'offText' => 'No',
    ]
]);
```
The checkbox is always checked. This is partly yii2 core's fault. See https://github.com/yiisoft/yii2/issues/1959. The fix for that issue is inside ```activeCheckbox()```, but doesn't apply to ```checkbox()```. Since SwitchInput uses ```checkbox()```, if there is a value set, the checkbox will always be marked as checked.

Can we perhaps allow SwitchInput to take a model as input or uncheck the checkbox if ```checked``` is set to ```FALSE```?

**Comment by kartik-v** [comment]
> Since SwitchInput uses checkbox() 

No that's not correct. Its because you have configured SwitchInput without a model. You can configure the SwitchInput to use a model attribute and then it will automatically use `activeCheckbox`

Check the [demo page for SwitchInput examples with model and with active form](http://demos.krajee.com/widget-details/switchinput#basic-usage).

For example:

```php
// SwitchInput with ActiveForm
echo $form->widget($model, 'attrib')->widget(SwitchInput::classname(), [//widget options]);

// SwitchInput without form but using model and model attrib
echo SwitchInput::widget([
    'model' => $model,
    'attribute' => 'attrib,
]);
```
